Host ldap01
    Hostname 172.26.42.15
Host campus-ldap03
    Hostname ldap-slave-03.zih.tu-dresden.de
Host campus-ldap04
    Hostname ldap-slave-04.zih.tu-dresden.de
Host campus-ldap05
    Hostname ldap-slave-05.zih.tu-dresden.de

Host cloudstore-ldap07
    Hostname ldap-slave-07.zih.tu-dresden.de
Host cloudstore-ldap08
    Hostname ldap-slave-08.zih.tu-dresden.de

Host infra-ldap09
    Hostname ldap-slave-09.zih.tu-dresden.de
Host infra-ldap10
    Hostname ldap-slave-10.zih.tu-dresden.de
Host infra-ldap11
    Hostname ldap-slave-11.zih.tu-dresden.de

Host oldssl-ldap12
    Hostname ldap-slave-12.zih.tu-dresden.de
Host oldssl-ldap13
    Hostname ldap-slave-13.zih.tu-dresden.de
